version: '3'
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        hostname: app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html/laranews.test
            - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        expose:
            - 80
        ports:
            - "80:80"
        links:
            - mysql
        depends_on:
            - mysql
        networks:
            - app-network

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=madhad
            - MYSQL_DATABASE=laradb
            - MYSQL_USER=n1oise
            - MYSQL_PASSWORD=madhad
        networks:
            - app-network
        volumes:
            - ./Docker/mysql:/var/lib/mysql

#Docker Networks
networks:
    app-network:
        driver: bridge
